# Generated by Django 3.2.9 on 2021-12-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='numAnswer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
